export const FIELDTYPE = {
  BigAutoField: 'BigAutoField',
  ForeignKey: 'ForeignKey',
  CharField: 'CharField',
  EmailField: 'EmailField',
  IntegerField: 'IntegerField',
  PositiveIntegerField: 'PositiveIntegerField',
  PositiveSmallIntegerField: 'PositiveSmallIntegerField',
  DecimalField: 'DecimalField',
  TextField: 'TextField',
  BooleanField: 'BooleanField',
  DateField: 'DateField',
  TimeField: 'TimeField',
  DateTimeField: 'DateTimeField',
  FileField: 'FileField',
  ImageField: 'ImageField',
  JSONField: 'JSONField',
  HTMLField: 'HTMLField',
  ManyToManyField: 'ManyToManyField',
  OneToOneField: 'OneToOneField',
  SlugField: 'SlugField',
}